server:
  port: 7017

spring:
  datasource:
    url: jdbc:mysql://tjubd.cn:3309/job_11
    username: root
    password: iemsIEMS2012
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
